### ISSUE TITLE
Working List View

### ISSUE THREAD

**Issue by FarhanHyder** [FarhanHyder/PooledHouse#36]
![image](https://user-images.githubusercontent.com/17440230/55983513-4de9cc00-5c69-11e9-941d-2a4f7048e0fa.png)
upon clicking on the list view there should be a list with some details. kinda like following?

| Area Name        | Zip          | Average | Mean|
| ------------- |:-------------:| -----:| -----:|
| area 1      | 11111 | $17.8 |  $16 |
| area 2    | 11112      |   $$11.8 |  $17.8 |
| area 3 | 11113      |    $10.0 |  $11.8 |

However, I do think this is not what our final list view should look like. Let me know your thoughts.  @IanMFraser  @shofi384  @ahamedbashir @dgarsir 

#### some notes
  - for this week - fill up the table with garbage values.
  - list view should be functioning with the search option

**Comment by ahamedbashir** [comment]
This will be the view for Guest user as the Guest user can't access business info.

**Comment by dgarsir** [comment]
@ahamedbashir I think because of the way authorization currently works, we're throwing out the Guest access feature for now, to be built back in later.

@FarhanHyder 
The list view is meant to have the following functionality:
- Show general average by area
- Show general average by area by day of the week (i.e. Mon, Tue....)
- Show general average by Business Name
- Show general average by Business Name by day of the week (i.e. Mon, Tue...)

I imagine the following

| Area Name | Zip | Average Shift Length | Average Tip |

**Comment by ahamedbashir** [comment]
@dgarsir , I am currently working on to process Tips data based on Business name. After finishing that up, I  can do the same based on area and and days. What you think?

**Comment by dgarsir** [comment]
@ahamedbashir, do you think you could restyle the list view so that it shows up in a horizontal, scrollable table? closer to what @FarhanHyder proposed in the first post.

**Comment by ahamedbashir** [comment]
@dgarsir sure, I will do that. For now I am keeping this like as it is just for easier testing.
