### ISSUE TITLE
figure out how the git fork/merge will work

### ISSUE THREAD

**Issue by FarhanHyder** [FarhanHyder/PooledHouse#4]
- figure out how git is used in a work environment
- research on branching vs forking

**Comment by shofi384** [comment]
As determined by the last meeting discussion, each member of the team will be working on their forked copy of the repo and make necessary push/pull to their own forked remote only.  
Once a merge to the master repo is necessary, the team member will submit a 'pull request' to the master repo and the rest is handled by the SCRUM master @FarhanHyder .  
Scrum master will, for each pull request, make a new branch and merge the requested changes to the new branch (**not the master branch**) to check the codes compatibility. If the new pull request is compatible with the master repo, SCRUM master will merge the changes to the master, otherwise he will reject the changes and the team member will have to work on the changes again and submit a new pull request.

**Comment by shofi384** [comment]
Restrict access to direct push to product owner's remote master repo
