### ISSUE TITLE
Issue: User doesn't want to keep adding data

### ISSUE THREAD

**Issue by IanMFraser** [FarhanHyder/PooledHouse#7]
A serious issue for PooledHouse is our users growing tired of continually inputting data week and week. If the user is not looking for a job, why would they want to keep giving data? Is it likely that the user might stop using the app once they got what they wanted?

**Comment by shofi384** [comment]
The question is if we should ask for a specific week's earning or should we collect an estimate/average of per week earnings. I guess collecting an estimate/average of per week earning might help solving the issue.

**Comment by FarhanHyder** [comment]
@shofi384 Although collecting an estimate/average data might look easy, I believe that might give the user to input data based on pure guesswork. (If they don't have the data saved somewhere)
On the other hand, inputting daily data will be very hard to collect, but it will give us very exact data. Therefore, we can produce the best result for our users as well. 

@IanMFraser I guess we can introduce the users with a feature that will help them keep track of their regular earning. So there can be two ways - 
1. The user's employer restaurant already use our system to keep track of their employee incomes (might be too advance for our project. But should be implemented later - as we discussed in the meeting). 
2. Provide the user enough functionalities so he/she can use our system to keep track of their income using our system. In order to do that, they will need to manually input their data regularly.

**Comment by IanMFraser** [comment]
One major point that might address this issue is making the UI as simple as possible. This way, it won't be tiresome for the user to contribute.
